import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

type LayoutPages = {
	params: { lang: string };
	children: React.ReactNode;
};
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, params }: LayoutPages) {
	const { lang } = params;
	return (
		<html lang={lang}>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
