export type AppString =
	| "appName"
	| "welcome-login-page"
	| "home"
	| "about-us"
	| "contact"
	| "login"
	| "hero-section-title"
	| "hero-section-description"
	| "get-your-free-consultation-now"
	| "get-started"
	| "go-to-homepage"
	| "remember-me"
	| "login-page-title"
	| "login-successfully"
	| "login-failed"
	| "logout-successfully";
